### ISSUE TITLE
Could you point me to data/model sources?

### ISSUE THREAD

**Issue by khrystyna-skopyk** [NohTow/PPL-MCTS#1]
Hello!

Thanks a lot for making your code available! 

I am trying to reproduce your paper, but I got a bit confused where I can get all the weights defined in `mcts_rollout_amazon.py`:

1. `model_path = "../datasets/amazon_polarity/full/models/validation_tokenfixed_BEST2021_06_16-17_35_02.pth"`
2. `gpt = GPT2LMHeadModel.from_pretrained("../../gpt2-amazon-notag-bigtraining-end")`
`tokenizer_gpt = GPT2TokenizerFast.from_pretrained("../../gpt2-amazon-notag-bigtraining-end")`
3. and a test file `data_lines = pd.read_csv("../datasets/amazon_polarity/full/dataset_test_2.tsv", sep='\t', engine='python', encoding="utf8")`

Could you point me where I can download those models and data?

I looked at huggingface but couldn't find neither `amazon_polarity/full/models/validation_tokenfixed_BEST2021_06_16-17_35_02.pth`, nor `gpt2-amazon-notag-bigtraining-end`.

Perhaps, you could also share the weights of discriminator?

Thanks a lot!

**Comment by NohTow** [comment]
Hello,

Thanks for your interest in PPL-MCTS (and for trying to reproduce results) !

Your confusion is totally justified: there is no available pointer to these weights/files. This is my mistake, I was looking for a sustainable storage solution and I totally forgot about it. Please excuse me for this. Uploading it on HF is a solution, yet this (old) implementation use a custom torch model extending HF models.

_Until I find a better solution, here is a link where you can find every file mentioned (discriminator, language model and tsv file used to build prompt) for the 3 datasets so you can go forward on your work: https://filesender.renater.fr/?s=download&token=fb74069e-9b8b-4f75-95f1-c82b466786ec_

_Again, sorry for the inconvenience, I'll definitely find a more convenient solution._

**Edit: we uploaded files on a sustainable storage, please use this link: [http://hoaxdetector.irisa.fr/data/PPL_MCTS_filetransfer.zip](http://hoaxdetector.irisa.fr/data/PPL_MCTS_filetransfer.zip)**

Good luck on your work !

**Comment by khrystyna-skopyk** [comment]
Thank you very much!
