### ISSUE TITLE
The data link is broken?

### ISSUE THREAD

**Issue by zfchenUnique** [NohTow/PPL-MCTS#4]
Hi, 

     Thank you for sharing the great work!
      Could you please help check that whether the download link is broken (http://hoaxdetector.irisa.fr/data/PPL_MCTS_filetransfer.zip ) ?
      I fail to download the data to follow the work.
      Thanks in advance again!

Regards,

**Comment by NohTow** [comment]
Hello,

The link seems indeed broken. I am so sorry about that and will try to fix it as soon as possible, but as mentioned in #3, the owner of the server is actually on vacation so for now, all I can do is just give you a temporary link: https://filesender.renater.fr/?s=download&token=5f0e234a-7dfc-443a-bd5f-bbf347010e56
(and here is the link for the weights of the second paper in case you were interested in these ones too: https://filesender.renater.fr/?s=download&token=321ed43c-95b6-4747-9d4b-7f3d8d617948)
Again, I am sorry, it will be fixed as soon as possible and I will close the issue only afterwards.

Thanks for noticing !

**Comment by NohTow** [comment]
Hello,

Links have been updated on the two readme, closing this issue now !
