### ISSUE TITLE
handling the MCTS terminal state

### ISSUE THREAD

**Issue by NatureGeorge** [NohTow/PPL-MCTS#7]
Hi, your work is very interesting. During my test of your pipeline, I encountered a problem related to the terminal state of MCTS.

The terminal state in the MCTS process means that a leaf node can not be further expanded and the game/generation reach its end.

I found your code records the terminal state status but never use it. e.g.
https://github.com/NohTow/PPL-MCTS/blob/ed588ca8f8abf4dd113f57d6c95c804ef9ca961e/mcts_rollout_amazon.py#L468

So I think there would be something wrong if the generation process actually reach its end.

**Comment by NohTow** [comment]
Hello,

Thanks for pointing this out, indeed, in this version of the code, the information of the node being terminal is not used.
In the next version of the code (for the Which Discriminator paper), e.g this one: [https://github.com/NohTow/PPL-MCTS/blob/main/teammates/mcts_ag_bert_bidi.py](https://github.com/NohTow/PPL-MCTS/blob/main/teammates/mcts_ag_bert_bidi.py), this information is used to stop the generation process early if all sequences in the batch are finished, force the token to be padding if the sequence is finished (to prevent generating a new sequence after the eos token) and fix the score of a finished sequence to the terminal node (although we keep exploring this one).


Hope this helps.

**Comment by NatureGeorge** [comment]
I see, thank you. :-)
